---
# Setup
seed: 100
saved_dir: ./saved_data
storage_dir: ./storage
# Data
transform:
  standard:
    random_resize_crop:
      size: 32
      scale: [0.2, 1.0]
    hflip:
      p: 0.5
    normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]
  test:
    center_crop:
      size: 32
    normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]
loader:
  batch_size: 128
  num_workers: 4
  pin_memory: True
# Model
network: resnet18_clbd
criterion:
  CrossEntropy: null
optimizer:
  SGD:
    weight_decay: 2.e-4
    momentum: 0.9
    lr: 0.1
# optimizer:
#   Adam:
#     lr: 0.001
lr_scheduler:
  MultiStepLR:
    milestones: [100, 150]
    gamma: 0.1
lr_scheduler: null
num_epochs: 200