---
seed:
  seed: 100
  deterministic: False
  benchmark: True
dataset_dir: ~/dataset/imagenet30
num_classes: 30
saved_dir: ./saved_data
storage_dir: ./storage
prefetch: True
torch_transforms:
  train:
    resize:
      size: 256
    center_crop:
      size: 224
    random_resize_crop:
      size: 224
      scale: [0.2, 1.0]
      interpolation: 3  # BICUBIC
    random_horizontal_flip:
      p: 0.5
    to_tensor: True
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  test:
    resize:
      size: 256
    center_crop:
      size: 224
    to_tensor: True
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
loader:
  batch_size: 256
  num_workers: 4
  pin_memory: True
network:
  resnet18_imagenet:
    num_classes: 30
sync_bn: True
criterion:
  cross_entropy:
    reduction: "mean"
optimizer:
  SGD:
    weight_decay: 1.e-4
    momentum: 0.9
    lr: 0.1  # 0.1 * batch_size / 256
lr_scheduler:
  multi_step:
    milestones: [30, 60]
    gamma: 0.1
num_epochs: 90